version: '3'
name: test-auth-service

services:
  auth-service:
    container_name: test-auth-service
    environment:
      - NODE_ENV=test
      - AUTH0_REDIRECT_URI=http://test-auth-service:3000/auth/callback
    env_file: .env.test
    # No healthcheck here

  redis-persistent:
    container_name: test-sol-redis-persistent-1
    volumes:
      - ./test-redis-data:/data

  redis-inmemory:
    container_name: test-sol-redis-inmemory-1

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test-runner-auth-service
    env_file: .env.test
    networks:
      - nucleus_network
    volumes:
      - ./tests:/app/tests
      - ./test-results:/app/test-results
    environment:
      - NODE_ENV=test
      - AUTH0_REDIRECT_URI=http://test-auth-service:3000/auth/callback
      - AUTH0_TEST_SERVER_REDIRECT_URI=http://test-runner-auth-service:3001/auth/callback
    depends_on:
      - auth-service
    # Sleep to give backend time to start
    command: >
      sh -c "
        echo 'Waiting for backend to start...' &&
        sleep 5 &&
        echo 'Running tests...' &&
        bun test
      "