version: '3'
name: test-provisioning

services:
  provisioning-backend:
    container_name: test-provisioning-backend
    environment:
      - NODE_ENV=test
      - AUTH0_REDIRECT_URI=http://test-provisioning-backend:3000/auth/callback
    env_file: .env.test
    # No healthcheck here

  redis-persistent:
    container_name: test-sol-redis-persistent
    volumes:
      - ./test-redis-data:/data

  redis-inmemory:
    container_name: test-sol-redis-inmemory

  freeradius:
    container_name: test-freeradius

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test-runner
    env_file: .env.test
    networks:
      - nucleus_network
    volumes:
      - ./tests:/app/tests
      - ./test-results:/app/test-results
    environment:
      - NODE_ENV=test
      - AUTH0_REDIRECT_URI=http://test-provisioning-backend:3000/auth/callback
      - AUTH0_TEST_SERVER_REDIRECT_URI=http://test-runner:3001/auth/callback
    depends_on:
      - provisioning-backend
    # Sleep to give backend time to start
    command: >
      sh -c "
        echo 'Waiting for backend to start...' &&
        sleep 5 &&
        echo 'Running tests...' &&
        bun test
      "