version: '3'
name: manual-test-auth-service

services:
  auth-service:
    container_name: manual-test-auth-service
    environment:
      - NODE_ENV=test
      - AUTH0_REDIRECT_URI=http://manual-test-auth-service:3000/auth/callback
    env_file: .env.test
    ports:
      - "3000:3000"  # Expose port to host machine for manual testing
    # No healthcheck here
    # Keep container running even if other services exit
    restart: unless-stopped

  redis-persistent:
    container_name: manual-test-sol-redis-persistent
    volumes:
      - ./test-redis-data:/data
    restart: unless-stopped

  redis-inmemory:
    container_name: manual-test-sol-redis-inmemory
    restart: unless-stopped

  # Make test-runner optional for manual testing
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: manual-test-runner
    env_file: .env.test
    networks:
      - nucleus_network
    volumes:
      - ./tests:/app/tests
      - ./test-results:/app/test-results
    environment:
      - NODE_ENV=test
      - AUTH0_REDIRECT_URI=http://manual-test-auth-service:3000/auth/callback
      - AUTH0_TEST_SERVER_REDIRECT_URI=http://manual-test-runner:3001/auth/callback
    depends_on:
      - auth-service
    # Sleep to give backend time to start
    command: >
      sh -c "
        echo 'Waiting for backend to start...' &&
        sleep 30 &&
        echo 'Running tests...' &&
        bun test
      "
    # This ensures the test-runner can exit without stopping other containers
    restart: "no"