version: '3'
name: test-auth-service

services:
  auth-service:
    container_name: test-auth-service
    environment:
      - NODE_ENV=test
    env_file: .env.test
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 60s

  redis-persistent:
    container_name: test-sol-redis-persistent-1
    volumes:
      - ./test-redis-data:/data  # Different data directory for tests

  redis-inmemory:
    container_name: test-sol-redis-inmemory-1

  # Add test runner service
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test-runner-auth-service
    env_file: .env.test
    networks:
      - nucleus_network
    volumes:
      - ./tests:/app/tests  # Mount tests directory
      - ./test-results:/app/test-results
    environment:
      - NODE_ENV=test
    depends_on:
      auth-service:
        condition: service_healthy
    command: bun test